server:
  port: 8080
  servlet:
    context-path: /entity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/entity_services"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true